image: wemulate/backend-cicd:1.0

cache:
  paths:
    - venv/

stages:
  - init
  - linting
  - build 
  
# before_script:
#   - "virtualenv backend"
#   - "source venv/bin/activate"
#   - "pip3 install -r requirements.txt"

init:
  stage: init
  script:
    - "virtualenv backend"
    - ". venv/bin/activate"
    - "pip3 install -r requirements.txt"
  
linting-site:
  stage: linting
  script:
    - "pylint interfaces"

# run_tests:
#   stage: test
#   script:
#     - "python tests.py"
  
build-site:
  stage: build
  script:
    - "cd interfaces/"
    - "tar cvfz ../wemulate-backend.tgz ./*"
  artifacts:
    expire_in: 1 week
    paths:
      - wemulate-backend.tgz
