image: wemulate/backend-cicd:1.0

cache:
  paths:
    - venv/

before_script:
  - "virtualenv venv"
  - "source venv/bin/activate"
  - "pip3 install -r requirements.txt"

stages:
  - linting
  - build 

linting-site:
  stage: linting
  script:
    - "flake8 --max-line-length=120 **/*.py"

pytest:
  stage: testing
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - python3 -m pytest

coverage:
  stage: testing
  script:
    - "python3 -m coverage run --source './' --omit './venv/*' -m pytest"
    - "coverage report -m"
  
build-docker:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - "docker build -f Dockerfile -t gitlab.dev.ifs.hsr.ch:45023/epj/2020/wemulate/wemulate-backend ."
    - "docker push gitlab.dev.ifs.hsr.ch:45023/epj/2020/wemulate/wemulate-backend"

