image: wemulate/backend-cicd:1.0

cache:
  paths:
    - venv/

stages:
  - init
  - linting
  - build 

init:
  stage: init
  script:
    - "virtualenv venv"
    - "source venv/bin/activate"
    - "pip3 install -r requirements.txt"
  
linting-site:
  stage: linting
  script:
    - "flake8 --max-line-length=120 **/*.py"

# run_tests:
#   stage: test
#   script:
#     - "python tests.py"
  
build-site:
  stage: build
  script:
    - "tar cvfz ../wemulate-backend.tgz ./*"
  artifacts:
    expire_in: 1 week
    paths:
      - wemulate-backend.tgz
