image: wemulate/backend-cicd:1.0

cache:
  paths:
    - venv/

stages:
  - init
  - linting
  - build 

init:
  stage: init
  script:
    - "virtualenv venv"
    - "source venv/bin/activate"
    - "pip3 install -r requirements.txt"
  
linting-site:
  stage: linting
  script:
    - "source venv/bin/activate"
    - "flake8 --max-line-length=120 **/*.py"
  
build-docker:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - "docker build -f Dockerfile -t gitlab.dev.ifs.hsr.ch:45023/epj/2020/wemulate/wemulate-backend ."
    - "docker push gitlab.dev.ifs.hsr.ch:45023/epj/2020/wemulate/wemulate-backend"

