name: Publish WEmulate API package to PyPi
on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish WEmulate to PyPi
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: JRubics/poetry-publish@v1.12
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
